apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: ml-sales-prediction-dp-rihel
spec:
description: Canary deployment strategy pipeline for ML Sales Predictor
serialPipeline:
  stages:
  - targetId: dev
    strategy:
      canary:
        runtimeConfig:
          cloudRun:
            automaticTrafficControl: true
        canaryDeployment:
          percentages: [25,75,100]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Dev env for ML Sales Predictor Cloud Run App
run:
  location: projects/faa-gcp-training-14-kfa-0808/locations/us-central1

------------